services:
  difficalcy-osu:
    build:
      context: .
      target: difficalcy-osu
    environment:
      - REDIS_CONFIGURATION=cache:6379
    volumes:
      - beatmaps:/home/app/beatmaps
    depends_on:
      - cache

  difficalcy-taiko:
    build:
      context: .
      target: difficalcy-taiko
    environment:
      - REDIS_CONFIGURATION=cache:6379
    volumes:
      - beatmaps:/home/app/beatmaps
    depends_on:
      - cache

  difficalcy-catch:
    build:
      context: .
      target: difficalcy-catch
    environment:
      - REDIS_CONFIGURATION=cache:6379
    volumes:
      - beatmaps:/home/app/beatmaps
    depends_on:
      - cache

  difficalcy-mania:
    build:
      context: .
      target: difficalcy-mania
    environment:
      - REDIS_CONFIGURATION=cache:6379
    volumes:
      - beatmaps:/home/app/beatmaps
    depends_on:
      - cache

  cache:
    image: redis:7
    volumes:
      - redis-data:/data

  docs:
    build: ./docs
    volumes:
      - ./docs:/docs

volumes:
  beatmaps:
  redis-data:
